import fuzzysort from "fuzzysort";


/**
* Run fuzzy search against foods and/or protocol templates.
*
* For searchType "food": returns foods only (used for Food B search).
* For searchType "protocol": returns protocols first, then foods (Food A search).
*
* @param query The user's search text
* @param searchType "food" (foods only) or "protocol" (protocols + foods)
* @param preparedFoods The array of prepared food objects (from fuzzySortPreparedFoods)
* @param preparedProtocols The array of prepared protocol objects (from fuzzySortPreparedProtocols)
* @returns Array of fuzzysort results (protocols may appear before foods)
*/
export function performSearch(query: string, searchType: "food" | "protocol", preparedFoods: any[], preparedProtocols: any[]): any[] {
  if (!query.trim()) return [];

  if (searchType === "food") {
    // Search foods only (for Food B)
    const results = fuzzysort.go(query, preparedFoods, {
      key: "prepared", // make use of the prepared property generated by fuzzysort.prepare(string)
      limit: 50,
      threshold: -10000,
    });
    return [...results];
  } else {
    // Search both foods and protocols for Food A
    const foodResults = fuzzysort.go(query, preparedFoods, {
      key: "prepared",
      limit: 25,
      threshold: -10000,
    });

    const protocolResults = fuzzysort.go(query, preparedProtocols, {
      key: "prepared",
      limit: 25,
      threshold: -10000,
    });

    // Combine results
    return [...protocolResults, ...foodResults];
  }
}
