# RULES:
# [medname] must be formatted as {generic (hyphenate if combination)} with {_route} if dramatically different from oral.
# for example: [budesonide_inhaler] because the oral form is used for EoE.
# similarly, [fluticasone-furoate_inhaler] - note the hyphenation used between the drug combos.

[template_med]
categories = ["testcategory", "testA", "testB"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[rupatadine]
categories = ["2G antihistamine"]
brand_names = ["Rupall", "Rupafin", "Rupita"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[bilastine]
categories = ["2G antihistamine"]
brand_names = ["Blexten"]
cost = [{ province = "ON", price = "~$1 CAD / 20mg tab" }]
moa = "2nd generation H1 antagonist."
half_life = "~15 hours"
routes = "PO tab, liquid (uncommon)"
doses = [
  { indication = "CSU, AR", dose = "20mg PO OD to QID", notes = "adult dosing" },
  { indication = "CSU, AR", dose = "10mg PO OD to QID", notes = "pediatric dosing" },
]
pearls = ["Theoretically does not cross BBB"]
age_group = ">=12 years of age; has been used off-label in younger children"
pregnancy = "Avoid (not enough data)"
contraindications = "Hypersensitivity, QT prolongation or history of torsades"
side_effects.common = "QT prolongation; drowsiness (4%); headache (4%). For reference, drowisness/headache had a 2% incidence rate in placebo arm"
side_effects.severe = "Torsades (very rare)"
monograph_links = ["../monographs/bilastine_2021_1.pdf"]

[loratadine]
categories = ["2G antihistamine"]
brand_names = ["Claritin", "Alavert"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[cetirizine]
categories = ["2G antihistamine"]
brand_names = ["Reactine", "Allacan"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[fexofenadine]
categories = ["2G antihistamine"]
brand_names = ["Allegra"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[desloratadine]
categories = ["2G antihistamine"]
brand_names = ["Aerius", "Clarinex"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[diphenhydramine]
categories = ["1G antihistamine"]
brand_names = ["Benadryl", "Nytol"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[salbutamol]
categories = ["inhaler", "SABA"]
brand_names = ["Ventolin", "Albuterol (not a brand name)"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[budesonide_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["Pulmicort Turbuhaler"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]


[fluticasone-furoate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["Arnuity Ellipta"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]


[fluticasone-propionate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]


[mometasone-furoate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[beclomethasone-dipropionate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]

[ciclesonide_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["../monographs/example_2025_1.pdf"]
