# RULES:
# [medname] must be formatted as {generic (hyphenate if combination)} with {_route} if dramatically different from oral.
# for example: [budesonide_inhaler] because the oral form is used for EoE.
# similarly, [fluticasone-furoate_inhaler] - note the hyphenation used between the drug combos.

[template_med]
categories = ["testcategory"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$X CAD / Ymg tab" },
  { province = "BC", price = "~$X CAD / Ymg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "yes" # only 'yes' or 'no' allowed
moa = "Insert MoA"
half_life = "~X hours"
peak_action = "Optional to add this in"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "Zmg OD", notes = "adult" },
  { indication = "diseaseA", dose = "Zmg OD", notes = "adult, CrCl < 30" },
  { indication = "diseaseB", dose = "Zmg BID", notes = "pediatric (ages X-Y)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""

###############################
# ANTIHISTAMINES
###############################

[rupatadine]
categories = ["2G antihistamine"]
brand_names = ["Rupall", "Rupafin", "Rupita"]
cost = [{ province = "ON", price = "~$0.99 CAD / 10mg tab" }]
coverage = [{ province = "ON", details = "ODB" }]
otc = "no"
moa = "2nd generation H1 receptor antagonist and platelet activating factor antagonist"
half_life = "~6 hours, but some metabolites (ie. desloratadine) remain longer; effects last ~24h"
peak_action = "Rapid absorption; maximal blood concentration in 1 hr"
routes = "oral 10 mg tab, liquid 1mg/ml"
doses = [
  { indication = "CSU, AR", dose = "10mg tab OD to QID", notes = "ages ≥12" },
  { indication = "CSU, AR", dose = "2.5mg liq OD to QID, ", notes = "10-25kg, ages 2-11" },
  { indication = "CSU, AR", dose = "5mg liq OD to QID, ", notes = ">25kg, ages 2-11" },
]
pearls = [
  "No data for hepatic or renal insufficiency",
  "Take with or without food (avoid grapefruit)",
  "Going more than OD is technically off-label",
]
age_group = "≥2 years old"
pregnancy = "Avoid (not enough data)"
contraindications = "Hypersensitivity, QT prolongation or history of Torsades"
side_effects.common = "Drowsiness 3-9%[D], 2-5%[P]; headache 1-6%[D], 2-5%[P]; tiredness 1%[D], 1%[P]; QT-prolongation 1%[D], <1%[P]; dizziness 1%[D], 1%[P]; nausea 0-2%[D], 1-2%[P]"
side_effects.severe = "All very rare (<1%): Torsades (only 1 event), liver enzyme elevation"
monograph_links = ["/monographs/rupatadine_2023_1.pdf"]
abbreviations = ""

[bilastine]
categories = ["2G antihistamine"]
brand_names = ["Blexten"]
cost = [{ province = "ON", price = "~$1.1 CAD / 20mg tab" }]
coverage = [{ province = "ON", details = "ODB" }]
otc = "no"
moa = "2nd generation H1 receptor antagonist"
half_life = "~15 hours"
peak_action = "~1h, rapid absorption"
routes = "10/20mg PO tab, 2.5mg/ml liquid (uncommon)"
doses = [
  { indication = "CSU, AR", dose = "20mg PO OD to QID", notes = "≥12 years old" },
  { indication = "CSU, AR", dose = "10mg PO OD to QID", notes = "4-11 years old" },
]
pearls = [
  "Theoretically does not cross BBB; less sedating than other AHs",
  "No renal adjustments needed; minimal data with hepatic impairment but not expected to cause issues",
  "Going beyond OD is technically off-label",
  "Take without food or juice otherwise absorption impaired",
]
age_group = "≥4 years old"
pregnancy = "Avoid (not enough data)"
contraindications = "Hypersensitivity, QT prolongation or history of torsades"
side_effects.common = "QT prolongation (at 100mg ODx4, max mean increase 6ms); drowsiness (4%); headache (4%). For reference, drowisness/headache had a 2% incidence rate in placebo arm"
side_effects.severe = "Torsades (very rare)"
monograph_links = ["/monographs/bilastine_2021_1.pdf"]
abbreviations = "CSU-chronic spontaneous urticaria; AR-allergic rhinitis"

[loratadine]
categories = ["2G antihistamine"]
brand_names = ["Claritin", "Alavert"]
cost = [{ province = "ON", price = "~$0.6 CAD / 10mg tab" }]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "2nd generation H1 receptor antagonist"
half_life = "8.4 hours (half life of active metabolite desloratadine is 28h)"
peak_action = ""
routes = "oral tab/capsule, solution"
doses = [
  { indication = "CSU, AR", dose = "10mg OD to QID", notes = ">= 6y" },
  { indication = "CSU, AR", dose = "10mg q48h", notes = "CrCl <30ml/min" },
  { indication = "CSU, AR", dose = "5mg OD to QID", notes = "ages [2,6)" },
]
pearls = [
  "No QTc prolongation noted in monographs or UpToDate. Mostly hepatically cleared, but in adults still renally adjust.",
]
age_group = "[2, adults) with dosing adjustments"
pregnancy = "Safe as per <a target='blank' href='https://www.acog.org/womens-health/experts-and-stories/ask-acog/what-medicine-can-i-take-for-allergies-while-im-pregnant'>ACOG</a> and <a target='blank' href='https://firstexposure.ca/seasonal-allergies-and-allergic-rhinitis-in-pregnancy-and-lactation/'>firstexposure</a>"
contraindications = "Hypersensitivity"
side_effects.common = "Fatigue, headache, dry mouth, drowsiness, nausea (~4-8%)"
side_effects.severe = "Essentially none reported in monograph."
monograph_links = ["/monographs/loratadine_2017_1.pdf"]
abbreviations = ""

[cetirizine]
categories = ["2G antihistamine"]
brand_names = ["Reactine", "Allacan"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""

[fexofenadine]
categories = ["2G antihistamine"]
brand_names = ["Allegra"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""

[desloratadine]
categories = ["2G antihistamine"]
brand_names = ["Aerius", "Clarinex"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""

[diphenhydramine]
categories = ["1G antihistamine"]
brand_names = ["Benadryl", "Nytol"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""

###############################
# PUFFERS
###############################

[salbutamol]
categories = ["inhaler", "SABA"]
brand_names = ["Ventolin", "Albuterol (not a brand name)"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""

[budesonide_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["Pulmicort Turbuhaler"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""


[fluticasone-furoate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["Arnuity Ellipta"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""


[fluticasone-propionate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""


[mometasone-furoate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""

[beclomethasone-dipropionate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""

[ciclesonide_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
peak_action = ""
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]
abbreviations = ""

###############################
# INCS
###############################
[mometasone-furoate_INCS]
categories = ["steroid", "INCS"]
brand_names = ["Nasonex", "Sinuva"]
cost = []
coverage = [{ province = "ON", details = "ODB" }]
otc = "no" # only 'yes' or 'no' allowed
moa = "Steroid, topical"
half_life = "~5.8 hours"
peak_action = "While monograph says ~12 hours, <b>maximal effect requires 2-4 weeks of use</b>"
routes = "nasal spray (50mcg)"
doses = [
  { indication = "AR", dose = "1-4 sprays (50mcg per spray) EN OD", notes = "≥12 years" },
  { indication = "AR", dose = "1 spray (50mcg per spray) EN OD", notes = "3-11 years" },
  { indication = "CRS", dose = "1-2 sprays (50mcg per spray) EN BID", notes = "≥12 years" },
]
pearls = [
  "2nd-generation INCS, **minimal systemic absorption (0.5%)**, no evidence of AI in PII and PIII studies",
  "For AR, classically useful for 'wet' nasal congestion",
  "**High** operator error; [see here for how to use](/handouts/incs/)",
  "OTC in the US; Rx in Canada",
]
age_group = "≥3 years"
pregnancy = "Maybe OK, but no adequate or well-controlled studies in pregnant or nursing women"
contraindications = "Hypersensitivity, acute bacterial sinus infection without antibiotics"
side_effects.common = "For adults: headache 8%[D], 6%[P]; epistaxis 8%[D], 5%[P], pharyngitis 4%[D], 3%[P]. For 3-11, all comparable to placebo"
side_effects.severe = "All very rare (<1%): liver enzyme elevation"
monograph_links = ["/monographs/mometasone-furoate_2021_1.pdf"]
abbreviations = "AR-allergic rhinitis; CRS-chronic rhinosinusitis; AI-adrenal insufficiency"


###############################
# TOPICAL STEROIDS
###############################

###############################
# EYE DROPS
###############################

###############################
# LTRAs
###############################

###############################
# EPINEPHRINE
###############################

###############################
# ANGIOEDEMA MEDS
###############################

###############################
# BIOLOGICS
###############################
