# RULES:
# [medname] must be formatted as {generic (hyphenate if combination)} with {_route} if dramatically different from oral.
# for example: [budesonide_inhaler] because the oral form is used for EoE.
# similarly, [fluticasone-furoate_inhaler] - note the hyphenation used between the drug combos.

[template_med]
categories = ["testcategory", "testA", "testB"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$X CAD / Ymg tab" },
  { province = "BC", price = "~$X CAD / Ymg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "yes" # only 'yes' or 'no' allowed
moa = "Insert MoA"
half_life = "~X hours"
peak_action = "Optional to add this in"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "Zmg OD", notes = "adult" },
  { indication = "diseaseA", dose = "Zmg OD", notes = "adult, CrCl < 30" },
  { indication = "diseaseB", dose = "Zmg BID", notes = "pediatric (ages X-Y)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]

###############################
# ANTIHISTAMINES
###############################

[rupatadine]
categories = ["2G antihistamine"]
brand_names = ["Rupall", "Rupafin", "Rupita"]
cost = [{ province = "ON", price = "~$0.99 CAD / 10mg tab" }]
coverage = [{ province = "ON", details = "ODB" }]
otc = "no"
moa = "2nd generation H1 receptor antagonist and platelet activating factor antagonist"
half_life = "~6 hours, but some metabolites (ie. desloratadine) remain longer; effects last ~24h"
peak_action = "Rapid absorption; maximal blood concentration in 1 hr"
routes = "oral 10 mg tab, liquid 1mg/ml"
doses = [
  { indication = "CSU, AR", dose = "10mg tab OD to QID", notes = "ages ≥12" },
  { indication = "CSU, AR", dose = "2.5mg liq OD to QID, ", notes = "10-25kg, ages 2-11" },
  { indication = "CSU, AR", dose = "5mg liq OD to QID, ", notes = ">25kg, ages 2-11" },
]
pearls = [
  "No data for hepatic or renal insufficiency",
  "Take with or without food (avoid grapefruit)",
  "Going more than OD is technically off-label",
]
age_group = "≥2 years old"
pregnancy = "Avoid (not enough data)"
contraindications = "Hypersensitivity, QT prolongation or history of Torsades"
side_effects.common = "Drowsiness (3-9%[D], 2-5%[P]); headache (1-6%[D], 2-5%[P]); tiredness (1%[D], 1%[P]); QT-prolongation (1%[D], <1%[P]); dizziness (1%[D], 1%[P]); nausea (0-2%[D], 1-2%[P])"
side_effects.severe = "All very rare (<1%): Torsades (only 1 event), liver enzyme elevation"
monograph_links = ["/monographs/rupatadine_2023_1.pdf"]

[bilastine]
categories = ["2G antihistamine"]
brand_names = ["Blexten"]
cost = [{ province = "ON", price = "~$1.1 CAD / 20mg tab" }]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "2nd generation H1 receptor antagonist."
half_life = "~15 hours"
routes = "PO tab, liquid (uncommon)"
doses = [
  { indication = "CSU, AR", dose = "20mg PO OD to QID", notes = "adult dosing" },
  { indication = "CSU, AR", dose = "10mg PO OD to QID", notes = "pediatric dosing" },
]
pearls = [
  "Theoretically does not cross BBB; less sedating than other AHs",
  "Take without food or juice otherwise absorption impaired",
]
age_group = "≥12 years old; used off-label in younger ages"
pregnancy = "Avoid (not enough data)"
contraindications = "Hypersensitivity, QT prolongation or history of torsades"
side_effects.common = "QT prolongation; drowsiness (4%); headache (4%). For reference, drowisness/headache had a 2% incidence rate in placebo arm"
side_effects.severe = "Torsades (very rare)"
monograph_links = ["/monographs/bilastine_2021_1.pdf"]

[loratadine]
categories = ["2G antihistamine"]
brand_names = ["Claritin", "Alavert"]
cost = [{ province = "ON", price = "~$0.6 CAD / 10mg tab" }]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "2nd generation H1 receptor antagonist"
half_life = "8.4 hours (half life of active metabolite--desloratadine--is 28h)"
routes = "oral tab/capsule, solution"
doses = [
  { indication = "CSU, AR", dose = "10mg OD to QID", notes = ">= 6y" },
  { indication = "CSU, AR", dose = "10mg q48h", notes = "CrCl <30ml/min" },
  { indication = "CSU, AR", dose = "5mg OD to QID", notes = "ages [2,6)" },
]
pearls = [
  "No QTc prolongation noted in monographs or UpToDate. Mostly hepatically cleared, but in adults still renally adjust.",
]
age_group = "[2, adults) with dosing adjustments"
pregnancy = "Safe as per [ACOG](https://www.acog.org/womens-health/experts-and-stories/ask-acog/what-medicine-can-i-take-for-allergies-while-im-pregnant) and [firstexposure](https://firstexposure.ca/seasonal-allergies-and-allergic-rhinitis-in-pregnancy-and-lactation/)"
contraindications = "Hypersensitivity"
side_effects.common = "Fatigue, headache, dry mouth, drowsiness, nausea (~4-8%)"
side_effects.severe = "Essentially none reported in monograph."
monograph_links = ["/monographs/loratadine_2017_1.pdf"]

[cetirizine]
categories = ["2G antihistamine"]
brand_names = ["Reactine", "Allacan"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]

[fexofenadine]
categories = ["2G antihistamine"]
brand_names = ["Allegra"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]

[desloratadine]
categories = ["2G antihistamine"]
brand_names = ["Aerius", "Clarinex"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]

[diphenhydramine]
categories = ["1G antihistamine"]
brand_names = ["Benadryl", "Nytol"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["Insert pearl here"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]

###############################
# PUFFERS
###############################

[salbutamol]
categories = ["inhaler", "SABA"]
brand_names = ["Ventolin", "Albuterol (not a brand name)"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]

[budesonide_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["Pulmicort Turbuhaler"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]


[fluticasone-furoate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["Arnuity Ellipta"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]


[fluticasone-propionate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]


[mometasone-furoate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]

[beclomethasone-dipropionate_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]

[ciclesonide_inhaler]
categories = ["inhaler", "steroid"]
brand_names = ["brandnameA", "brandnameB"]
cost = [
  { province = "ON", price = "~$0.50 CAD / 10mg tab" },
  { province = "BC", price = "~$1000 CAD / 10mg tab" },
]
coverage = [
  { province = "ON", details = "enter details" },
  { province = "BC", details = "enter details" },
]
otc = "no"
moa = "Insert MoA"
half_life = "~X hours"
routes = "oral tab, liquid, ODT"
doses = [
  { indication = "diseaseA", dose = "180mg OD", notes = "adult" },
  { indication = "diseaseB", dose = "30mg BID", notes = "pediatric (ages 2-11)" },
]
pearls = ["[inhalerguide.ca](https://www.inhalerguide.ca/)"]
age_group = "insert age group"
pregnancy = "insert information, can link to data"
contraindications = "insert"
side_effects.common = "insert"
side_effects.severe = "insert"
monograph_links = ["/monographs/example_2025_1.pdf"]

###############################
# INCS
###############################

###############################
# TOPICAL STEROIDS
###############################

###############################
# EYE DROPS
###############################

###############################
# LTRAs
###############################

###############################
# EPINEPHRINE
###############################

###############################
# ANGIOEDEMA MEDS
###############################

###############################
# BIOLOGICS
###############################
