# Used for the editor bios in the about section

[title1]
src = "/images/profile_jy.png"
name = "Joshua Yu, MD BSc"
text = "PGY-3 IM resident at McMaster, fellow-to-be at UBC."
[title2]
src = "/images/profile_am.png"
name = "Adhora Mir"
text = "PGY-4 Adult Allergy & Immunology resident at McGill University."
[title3]
src = "/images/example.png"
name = "Editor 3"
text = "Could also be you!"
