# Topic -- the way you want it to appear on the website
# keywords -- part of the search index for the fuzzy find
# content -- plain text macro

[_consult]
topic = "Consult template"
keywords = ["template", "consult"]
content = '''
CLINICAL ALLERGY AND IMMUNOLOGY CONSULTATION

We assessed this patient in the clinical allergy and immunology clinic today on {current_date} with Dr. ***.
As you know, they are a *** referred for assessment of ***.

PAST MEDICAL HISTORY:

ATOPIC HISTORY:
Asthma:
Food allergies:
Drug allergies:
Venom allergies:
Eczema:
Rhinitis:

MEDICATIONS:

FAMILY HISTORY:

SOCIAL HISTORY:
Home environment:
Occupation:
Private coverage:
Smoking:
Pets:

If pediatric:
PRENATAL/OB:

VACCINATIONS:

DEVELOPMENT:

HISTORY OF PRESENTING ILLNESS:

PHYSICAL EXAM:
On physical examination, they were not in distress.
Assessment of the head and neck reveled no conjunctival injection. Anterior rhinoscopy showed no turbinate edema with no nasal secretions, mucosal pallor, or polyps. The oropharynx was unremarkable with no cobblestoning or erythema.
Respiratory examination revealed no work of breathing and full air entry equally bilaterally with no wheeze or crackles. Cardiovascular exam revealed normal S1 and S2 with no extra heart sounds or murmurs.
There were no rashes present on examination of the skin.

INVESTIGATIONS:

Skin prick testing:

IMPRESSION:

PLAN:

FOLLOW-UP:
We have not arranged any follow-up at this time, but they are welcome to contact us as required.
We have arranged for follow-up in *** or sooner if required.

Thank you for allowing us to take part in this patient's care. Please feel free to contact us if there are any questions or concerns.

Sincerely,
'''

[_followup]
topic = "Follow-up template"
keywords = ["template", "follow up"]
content = '''
CLINICAL ALLERGY AND IMMUNOLOGY FOLLOW-UP

Dr. *** and I saw this patient in follow up in the Clinical Immunology and Allergy Clinic on {current_date}.
They were last seen on *** previously.
As you know, they are a *** who we follow for ***.

Their last assessment and plan was:

RELEVANT ALLERGIC AND MEDICAL HISTORY:

CURRENT MEDICATIONS:

INTERVAL HISTORY:

[Issue by issue]

Otherwise:

PHYSICAL EXAM:
On physical examination, they were not in distress.
Assessment of the head and neck reveled no conjunctival injection. Anterior rhinoscopy showed no turbinate edema with no nasal secretions, mucosal pallor, or polyps. The oropharynx was unremarkable with no cobblestoning or erythema.
Respiratory examination revealed no work of breathing and full air entry equally bilaterally with no wheeze or crackles. Cardiovascular exam revealed normal S1 and S2 with no extra heart sounds or murmurs.
There were no rashes present on examination of the skin.

INVESTIGATIONS:

ASSESSMENT AND PLAN:

FOLLOW-UP:
We have not arranged any follow-up at this time, but they are welcome to contact us as required.
We have arranged for follow-up in *** or sooner if required.

Thank you once again for involving us in this patient's care. Please do not hesitate to contact us if you have any further questions or concerns.

Sincerely,
'''

# PROCEDURES / NON CONDITIONS 
# -----------------------------
[oral_food_challenge]
topic = "Oral Challenge"
keywords = ["OFC", "oral food challenge"]
content = '''
Placeholder macro  
'''

[drug_challenge]
topic = "Drug Challenge"
keywords = ["direct drug challenge", "drug challenge"]
content = '''
Placeholder macro  
'''

[scit_injection]
topic = "SCIT injection"
keywords = ["tbd"]
content = '''
Placeholder macro  
'''

[slit_initiation]
topic = "SLIT initiation"
keywords = ["tbd"]
content = '''
Placeholder macro  
'''

[patch_test]
topic = "Patch test"
keywords = ["tbd"]
content = '''
Placeholder macro  
'''

# CONDITIONS
# -----------------------------

[allergic_rhinitis]
topic = "Allergic Rhinitis"
keywords = ["rhinitis", "ar", "rhinosinusitis"]
content = '''
Placeholder macro  
'''

[chronic_rhinosinusitis]
topic = "Chronic rhinosinusitis"
keywords = ["CRS", "sinusitis", "polyp"]
content = '''
nasal congestion/fullness
facial pain/pressure/fullness
anterior or posterior nasal drainage (?purulent)
hypo/anosmia
change in voice
cough
headache
fatigue/disruption of sleep
halitosis/dental pain
ear pain/fullness
duration
CT/ENT before? Known nasal polyps?
? asthma/COPD, AR, CF, NERD/ASA sensitivity, recurrent infect, EtOH induced worsening of upper airway disease, impaired cilia(CF, PCD), smoking, pollution, occupational exposure, nasal anatomic variations, vasculitis
Treatment trials
SNOT-22 Score

# Chronic rhinosinusitis (CRS) wNP sNP AFRS
Their clinical picture is suggestive of CRS, an inflammatory syndrome defined by objective structural evidence of sinus inflammation and ≥2 cardinal symptoms (nasal congestion, facial pain/pressure, anterior/posterior nasal drainage, absent/reduced smell) ≥12 weeks. While chronic, regular pharmacotherapy can usually control symptoms well.

Recommendations:
- CT sinuses (non-contrast) vs ENT referral
- SPT for common aeroallergens
- Ad-hoc testing: ie. B-cell immunodeficiency workup in setting of suspicious symptoms / acute recurrent sinusitis
- High volume nasal saline rinses, avoidance of triggers
- INCS + treatment of any underlying causes
- Consider short course prednisone for symptom management (most evidence for CRSwNP or AFRS)
- Consider oral antibiotics for acute exacerbations (controversial)
- Consider biologics for CRSwNP if severe/failed first-line therapy
- Follow-up: ~3-4 months
'''
